services:
  - type: web
    name: traffic-manager-puppeteer
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: srv1660.hstgr.io
      - key: DB_USER
        value: u737449533_traffic
      - key: DB_PASS
        value: Traffic2025!
      - key: DB_NAME
        value: u737449533_traffic
